openapi: 3.0.1
info:
  title: netlist-visualizer-service
  description: Backend for netlist visualizer
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: Users
  description: Simple user endpoints
- name: Specification
  description: The swagger API specification
paths:
  /users:
    get:
      tags:
      - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
          content: {}
    post:
      tags:
      - Users
      description: Create a new user
      requestBody:
        description: an user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBody'
        required: true
      responses:
        201:
          description: Returns the id of the created user
          content: {}
  /users/{id}:
    get:
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: The id of the user to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Return the user with the specified id
          content: {}
        404:
          description: User not found
          content: {}
    put:
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: The id of the user to retrieve
        required: true
        schema:
          type: string
      requestBody:
        description: an user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBody'
        required: true
      responses:
        200:
          description: Return the user
          content: {}
        404:
          description: User not found
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    UserBody:
      title: user
      required:
      - email
      type: object
      properties:
        email:
          type: string
          example: test@email.com
